#ifndef __PaycheckHelperMainPanel__
#define __PaycheckHelperMainPanel__

/**
@file
Subclass of MainPanel, which is generated by wxFormBuilder.
*/

#include "pHelper.h"

/** Implementing MainPanel */
class PaycheckHelperMainPanel : public MainPanel
{
protected:
	// Handlers for MainPanel events.
	void OnGross( wxCommandEvent& event );
	void OnFiling( wxCommandEvent& event );
	void OnExemptions( wxCommandEvent& event );
	void OnPeriod( wxCommandEvent& event );
	void OnCalculate( wxCommandEvent& event );
	
public:
	/** Constructor */
	PaycheckHelperMainPanel( wxWindow* parent );
};

#endif // __PaycheckHelperMainPanel__
